# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", nil) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  primary: &primary_production
    <<: *default
    database: chat_app_production
    username: chat_app
    password: <%= ENV["CHAT_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: chat_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: chat_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: chat_app_production_cable
    migrations_paths: db/cable_migrate
